import { useState, useEffect } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { DatePickerString } from "@/components/ui/date-picker";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { Switch } from "@/components/ui/switch";
import {
  Plus,
  Trash2,
  DollarSign,
  Send,
  RefreshCw,
} from "lucide-react";
import { toast } from "sonner";

interface EditInvoiceModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  invoice: {
    id: string;
    customer: string;
    amount: string;
    date: string;
    dueDate: string;
    status: string;
    qbStatus: string;
    jobId: string;
    paymentMethod: string;
    autoGenerated: boolean;
    qbInvoiceId: string;
  } | null;
}

const services = [
  { name: "Regular Clean", price: 120 },
  { name: "Deep Clean", price: 180 },
  { name: "Move-in Clean", price: 250 },
  { name: "Move-out Clean", price: 280 },
  { name: "Post-construction Clean", price: 350 },
  { name: "Office Clean", price: 200 },
];

const paymentTermsOptions = [
  { value: "due_on_receipt", label: "Due on Receipt" },
  { value: "net15", label: "Net 15" },
  { value: "net30", label: "Net 30" },
  { value: "net45", label: "Net 45" },
  { value: "net60", label: "Net 60" },
];

const statusOptions = [
  { value: "draft", label: "Draft" },
  { value: "sent", label: "Sent" },
  { value: "payment_pending", label: "Payment Pending" },
  { value: "paid", label: "Paid" },
  { value: "complete", label: "Complete" },
  { value: "overdue", label: "Overdue" },
];

interface LineItem {
  id: string;
  description: string;
  quantity: number;
  unitPrice: number;
}

export function EditInvoiceModal({ open, onOpenChange, invoice }: EditInvoiceModalProps) {
  const [formData, setFormData] = useState({
    customer: "",
    issueDate: "",
    dueDate: "",
    paymentTerms: "net30",
    jobId: "",
    status: "sent",
    notes: "",
    resendToCustomer: false,
    syncToQB: true,
    taxRate: 0,
    totalPayment: 0,
    createdDate: "",
    sentDate: "",
    openDate: "",
    paidDate: "",
    receiptDate: "",
  });

  const [lineItems, setLineItems] = useState<LineItem[]>([
    { id: "1", description: "", quantity: 1, unitPrice: 0 },
  ]);

  // Parse amount from invoice to initialize line items
  useEffect(() => {
    if (invoice) {
      const amountValue = parseFloat(invoice.amount.replace("$", "").replace(",", ""));
      
      setFormData({
        customer: invoice.customer,
        issueDate: invoice.date,
        dueDate: invoice.dueDate,
        paymentTerms: "net30",
        jobId: invoice.jobId,
        status: invoice.status,
        notes: "",
        resendToCustomer: false,
        syncToQB: true,
        taxRate: 0,
        totalPayment: 0,
        createdDate: invoice.date,
        sentDate: "",
        openDate: "",
        paidDate: invoice.status === "paid" ? invoice.date : "",
        receiptDate: "",
      });

      // Initialize with a single line item with the invoice amount
      setLineItems([
        { id: "1", description: "Cleaning Service", quantity: 1, unitPrice: amountValue },
      ]);
    }
  }, [invoice]);

  const addLineItem = () => {
    setLineItems([
      ...lineItems,
      { id: Date.now().toString(), description: "", quantity: 1, unitPrice: 0 },
    ]);
  };

  const removeLineItem = (id: string) => {
    if (lineItems.length > 1) {
      setLineItems(lineItems.filter((item) => item.id !== id));
    }
  };

  const updateLineItem = (id: string, field: keyof LineItem, value: string | number) => {
    setLineItems(
      lineItems.map((item) =>
        item.id === id ? { ...item, [field]: value } : item
      )
    );
  };

  const subtotal = lineItems.reduce(
    (sum, item) => sum + item.quantity * item.unitPrice,
    0
  );

  const handleSave = () => {
    if (lineItems.every((item) => item.unitPrice === 0)) {
      toast.error("Please add at least one line item with a value");
      return;
    }

    toast.success("Invoice updated successfully");
    
    if (formData.resendToCustomer) {
      toast.info(`Invoice resent to ${formData.customer}`);
    }
    
    if (formData.syncToQB) {
      toast.info("Syncing changes to QuickBooks...");
    }
    
    onOpenChange(false);
  };

  const handleResend = () => {
    toast.success(`Invoice resent to ${formData.customer}`);
  };

  if (!invoice) return null;

  const getStatusColor = (status: string) => {
    switch (status) {
      case "paid": return "default";
      case "sent": return "secondary";
      case "payment_pending": return "secondary";
      case "complete": return "default";
      case "overdue": return "destructive";
      case "draft": return "outline";
      default: return "default";
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[700px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex items-center justify-between">
            <DialogTitle className="flex items-center gap-2">
              <DollarSign className="w-5 h-5 text-primary" />
              Edit Invoice {invoice.id}
            </DialogTitle>
            <Badge variant={getStatusColor(formData.status)}>
              {formData.status.replace("_", " ")}
            </Badge>
          </div>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* Customer Info (Read-only) */}
          <div className="p-4 rounded-lg border bg-muted/30">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label className="text-xs text-muted-foreground">Customer</Label>
                <p className="font-medium text-foreground">{formData.customer}</p>
              </div>
              <div>
                <Label className="text-xs text-muted-foreground">QB Invoice ID</Label>
                <p className="font-medium text-foreground">{invoice.qbInvoiceId}</p>
              </div>
            </div>
          </div>

          {/* Editable Fields */}
          <div className="grid grid-cols-3 gap-4">
            <div className="space-y-2">
              <Label>Issue Date</Label>
              <DatePickerString
                value={formData.issueDate}
                onChange={(value) =>
                  setFormData({ ...formData, issueDate: value })
                }
                placeholder="Select issue date"
              />
            </div>

            <div className="space-y-2">
              <Label>Payment Terms</Label>
              <Select
                value={formData.paymentTerms}
                onValueChange={(value) =>
                  setFormData({ ...formData, paymentTerms: value })
                }
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-popover border-border">
                  {paymentTermsOptions.map((term) => (
                    <SelectItem key={term.value} value={term.value}>
                      {term.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Status</Label>
              <Select
                value={formData.status}
                onValueChange={(value) =>
                  setFormData({ ...formData, status: value })
                }
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-popover border-border">
                  {statusOptions.map((status) => (
                    <SelectItem key={status.value} value={status.value}>
                      {status.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="space-y-2">
            <Label>Job ID</Label>
            <Input
              value={formData.jobId}
              onChange={(e) => setFormData({ ...formData, jobId: e.target.value })}
              placeholder="JOB-001"
            />
          </div>

          <Separator />

          {/* Line Items */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <Label className="text-base font-semibold">Line Items</Label>
              <Button variant="outline" size="sm" onClick={addLineItem}>
                <Plus className="w-4 h-4 mr-2" />
                Add Item
              </Button>
            </div>

            <div className="space-y-3">
              {lineItems.map((item, index) => (
                <div
                  key={item.id}
                  className="grid grid-cols-12 gap-3 items-start"
                >
                  <div className="col-span-5 space-y-1">
                    {index === 0 && (
                      <Label className="text-xs text-muted-foreground">
                        Description
                      </Label>
                    )}
                    <Select
                      value={item.description}
                      onValueChange={(value) => {
                        const service = services.find((s) => s.name === value);
                        updateLineItem(item.id, "description", value);
                        if (service) {
                          updateLineItem(item.id, "unitPrice", service.price);
                        }
                      }}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select service..." />
                      </SelectTrigger>
                      <SelectContent className="bg-popover border-border">
                        <SelectItem value="Cleaning Service">Cleaning Service (Custom)</SelectItem>
                        {services.map((service) => (
                          <SelectItem key={service.name} value={service.name}>
                            {service.name} - ${service.price}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="col-span-2 space-y-1">
                    {index === 0 && (
                      <Label className="text-xs text-muted-foreground">Qty</Label>
                    )}
                    <Input
                      type="number"
                      min="1"
                      value={item.quantity}
                      onChange={(e) =>
                        updateLineItem(item.id, "quantity", parseInt(e.target.value) || 1)
                      }
                    />
                  </div>

                  <div className="col-span-2 space-y-1">
                    {index === 0 && (
                      <Label className="text-xs text-muted-foreground">
                        Unit Price
                      </Label>
                    )}
                    <Input
                      type="number"
                      min="0"
                      step="0.01"
                      value={item.unitPrice}
                      onChange={(e) =>
                        updateLineItem(item.id, "unitPrice", parseFloat(e.target.value) || 0)
                      }
                    />
                  </div>

                  <div className="col-span-2 space-y-1">
                    {index === 0 && (
                      <Label className="text-xs text-muted-foreground">Total</Label>
                    )}
                    <div className="h-10 flex items-center font-medium">
                      ${(item.quantity * item.unitPrice).toFixed(2)}
                    </div>
                  </div>

                  <div className="col-span-1 space-y-1">
                    {index === 0 && <Label className="text-xs invisible">X</Label>}
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={() => removeLineItem(item.id)}
                      disabled={lineItems.length === 1}
                    >
                      <Trash2 className="w-4 h-4 text-muted-foreground" />
                    </Button>
                  </div>
                </div>
              ))}
            </div>

            {/* Totals Section */}
            <div className="pt-4 border-t space-y-2">
              <div className="flex justify-between items-center">
                <span className="text-sm text-muted-foreground">Subtotal</span>
                <span className="font-medium">${subtotal.toFixed(2)}</span>
              </div>
              <div className="flex justify-between items-center">
                <div className="flex items-center gap-2">
                  <span className="text-sm text-muted-foreground">Tax</span>
                  <Input
                    type="number"
                    min="0"
                    max="100"
                    step="0.1"
                    value={formData.taxRate}
                    onChange={(e) => setFormData({ ...formData, taxRate: parseFloat(e.target.value) || 0 })}
                    className="w-16 h-7 text-xs"
                  />
                  <span className="text-sm text-muted-foreground">%</span>
                </div>
                <span className="font-medium">${(subtotal * formData.taxRate / 100).toFixed(2)}</span>
              </div>
              <Separator className="my-2" />
              <div className="flex justify-between items-center">
                <span className="text-sm font-medium">Total Charges</span>
                <span className="font-semibold">${(subtotal + (subtotal * formData.taxRate / 100)).toFixed(2)}</span>
              </div>
              <Separator className="my-2" />
              <div className="flex justify-between items-center">
                <span className="text-sm text-muted-foreground">Total Payment</span>
                <div className="flex items-center gap-1">
                  <span className="text-muted-foreground">$</span>
                  <Input
                    type="number"
                    min="0"
                    step="0.01"
                    value={formData.totalPayment}
                    onChange={(e) => setFormData({ ...formData, totalPayment: parseFloat(e.target.value) || 0 })}
                    className="w-24 h-7 text-right"
                  />
                </div>
              </div>
              <Separator className="my-2" />
              <div className="flex justify-between items-center">
                <span className="text-base font-semibold">Total Due</span>
                <span className="text-lg font-bold text-foreground">
                  ${((subtotal + (subtotal * formData.taxRate / 100)) - formData.totalPayment).toFixed(2)}
                </span>
              </div>
            </div>
          </div>

          <Separator />

          {/* Invoice Dates Grid */}
          <div className="space-y-3">
            <Label className="text-base font-semibold">Invoice Timeline</Label>
            <div className="grid grid-cols-5 gap-3">
              <div className="space-y-1">
                <Label className="text-xs text-muted-foreground">Created</Label>
                <DatePickerString
                  value={formData.createdDate}
                  onChange={(value) => setFormData({ ...formData, createdDate: value })}
                  placeholder="--"
                  buttonClassName="h-9 text-xs"
                />
              </div>
              <div className="space-y-1">
                <Label className="text-xs text-muted-foreground">Sent</Label>
                <DatePickerString
                  value={formData.sentDate}
                  onChange={(value) => setFormData({ ...formData, sentDate: value })}
                  placeholder="--"
                  buttonClassName="h-9 text-xs"
                />
              </div>
              <div className="space-y-1">
                <Label className="text-xs text-muted-foreground">Open</Label>
                <DatePickerString
                  value={formData.openDate}
                  onChange={(value) => setFormData({ ...formData, openDate: value })}
                  placeholder="--"
                  buttonClassName="h-9 text-xs"
                />
              </div>
              <div className="space-y-1">
                <Label className="text-xs text-muted-foreground">Paid</Label>
                <DatePickerString
                  value={formData.paidDate}
                  onChange={(value) => setFormData({ ...formData, paidDate: value })}
                  placeholder="--"
                  buttonClassName="h-9 text-xs"
                />
              </div>
              <div className="space-y-1">
                <Label className="text-xs text-muted-foreground">Receipt</Label>
                <DatePickerString
                  value={formData.receiptDate}
                  onChange={(value) => setFormData({ ...formData, receiptDate: value })}
                  placeholder="--"
                  buttonClassName="h-9 text-xs"
                />
              </div>
            </div>
          </div>

          <Separator />

          {/* Notes */}
          <div className="space-y-2">
            <Label>Notes (optional)</Label>
            <Textarea
              value={formData.notes}
              onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
              placeholder="Reason for changes or additional notes..."
              rows={3}
            />
          </div>

          {/* Options */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <Label>Resend to Customer</Label>
                <p className="text-sm text-muted-foreground">
                  Send updated invoice to the customer after saving
                </p>
              </div>
              <Switch
                checked={formData.resendToCustomer}
                onCheckedChange={(checked) =>
                  setFormData({ ...formData, resendToCustomer: checked })
                }
              />
            </div>

            <div className="flex items-center justify-between">
              <div>
                <Label>Sync to QuickBooks</Label>
                <p className="text-sm text-muted-foreground">
                  Update this invoice in QuickBooks
                </p>
              </div>
              <Switch
                checked={formData.syncToQB}
                onCheckedChange={(checked) =>
                  setFormData({ ...formData, syncToQB: checked })
                }
              />
            </div>
          </div>
        </div>

        <DialogFooter className="flex-col sm:flex-row gap-2">
          <Button variant="outline" onClick={handleResend} className="sm:mr-auto">
            <Send className="w-4 h-4 mr-2" />
            Resend Now
          </Button>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button onClick={handleSave}>
            <RefreshCw className="w-4 h-4 mr-2" />
            Save Changes
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
