import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Plus,
  Search,
  DollarSign,
  CreditCard,
  AlertCircle,
  Clock,
  CheckCircle,
} from "lucide-react";
import { CreateInvoiceModal } from "@/components/billing/CreateInvoiceModal";
import { EditInvoiceModal } from "@/components/billing/EditInvoiceModal";

const invoicesData = [
  {
    id: "INV-001",
    customer: "Sarah Johnson",
    amount: "$180.00",
    date: "2024-01-15",
    dueDate: "2024-01-30",
    status: "paid",
    qbStatus: "synced",
    jobId: "JOB-001",
    paymentMethod: "Credit Card",
    autoGenerated: true,
    qbInvoiceId: "QB-10234"
  },
  {
    id: "INV-002",
    customer: "Tech Startup Inc.",
    amount: "$120.00",
    date: "2024-01-15",
    dueDate: "2024-02-15",
    status: "sent",
    qbStatus: "sent",
    jobId: "JOB-002",
    paymentMethod: "ACH",
    autoGenerated: true,
    qbInvoiceId: "QB-10235"
  },
  {
    id: "INV-003",
    customer: "Miller Family",
    amount: "$280.00",
    date: "2024-01-10",
    dueDate: "2024-01-25",
    status: "payment_pending",
    qbStatus: "pending",
    jobId: "JOB-003",
    paymentMethod: "Check",
    autoGenerated: true,
    qbInvoiceId: "QB-10236"
  },
  {
    id: "INV-004",
    customer: "Downtown Office Complex",
    amount: "$450.00",
    date: "2024-01-20",
    dueDate: "2024-02-05",
    status: "overdue",
    qbStatus: "sent",
    jobId: "JOB-004",
    paymentMethod: "ACH",
    autoGenerated: true,
    qbInvoiceId: "QB-10237"
  },
  {
    id: "INV-005",
    customer: "Green Valley Apartments",
    amount: "$325.00",
    date: "2024-01-22",
    dueDate: "2024-02-07",
    status: "complete",
    qbStatus: "paid",
    jobId: "JOB-005",
    paymentMethod: "Credit Card",
    autoGenerated: true,
    qbInvoiceId: "QB-10238"
  }
];

export function InvoicesTab() {
  const [searchTerm, setSearchTerm] = useState("");
  const [searchField, setSearchField] = useState("all");
  const [createInvoiceOpen, setCreateInvoiceOpen] = useState(false);
  const [editInvoiceOpen, setEditInvoiceOpen] = useState(false);
  const [selectedInvoice, setSelectedInvoice] = useState<typeof invoicesData[0] | null>(null);

  const handleEditInvoice = (invoice: typeof invoicesData[0]) => {
    setSelectedInvoice(invoice);
    setEditInvoiceOpen(true);
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "paid": return "default";
      case "sent": return "secondary";
      case "payment_pending": return "secondary";
      case "complete": return "default";
      case "overdue": return "destructive";
      case "draft": return "outline";
      default: return "default";
    }
  };

  return (
    <div className="space-y-6">
      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">Total Revenue</p>
                <p className="text-2xl font-bold text-foreground">$45,280</p>
                <p className="text-sm text-success">+18% from last month</p>
              </div>
              <div className="p-3 bg-primary/10 rounded-lg">
                <DollarSign className="w-6 h-6 text-primary" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">Paid Invoices</p>
                <p className="text-2xl font-bold text-foreground">298</p>
                <p className="text-sm text-success">94.2% collection rate</p>
              </div>
              <div className="p-3 bg-success/10 rounded-lg">
                <CreditCard className="w-6 h-6 text-success" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">Payment Pending</p>
                <p className="text-2xl font-bold text-foreground">8</p>
                <p className="text-sm text-warning">$1,950 awaiting payment</p>
              </div>
              <div className="p-3 bg-warning/10 rounded-lg">
                <Clock className="w-6 h-6 text-warning" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-muted-foreground">Overdue</p>
                <p className="text-2xl font-bold text-foreground">3</p>
                <p className="text-sm text-destructive">$840 past due</p>
              </div>
              <div className="p-3 bg-destructive/10 rounded-lg">
                <AlertCircle className="w-6 h-6 text-destructive" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Invoices Table */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle>Invoices</CardTitle>
            <Button variant="hero" size="sm" onClick={() => setCreateInvoiceOpen(true)}>
              <Plus className="w-4 h-4 mr-2" />
              Create Invoice
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="flex items-center gap-4 mb-6">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input
                placeholder="Search invoices..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-10 bg-background border-border"
              />
            </div>
            <Select value={searchField} onValueChange={setSearchField}>
              <SelectTrigger className="w-[160px] bg-background border-border">
                <SelectValue placeholder="Search by" />
              </SelectTrigger>
              <SelectContent className="bg-popover border-border">
                <SelectItem value="all">All</SelectItem>
                <SelectItem value="invoice">Invoice ID</SelectItem>
                <SelectItem value="customer">Customer</SelectItem>
                <SelectItem value="jobId">Job ID</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Invoice ID</TableHead>
                <TableHead>Job ID</TableHead>
                <TableHead>Customer</TableHead>
                <TableHead>Amount</TableHead>
                <TableHead>Issue Date</TableHead>
                <TableHead>Due Date</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Auto-Gen</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {invoicesData
                .filter((invoice) => {
                  const search = searchTerm.toLowerCase();
                  if (!searchTerm) return true;
                  if (searchField === "all") {
                    return (
                      invoice.id.toLowerCase().includes(search) ||
                      invoice.customer.toLowerCase().includes(search) ||
                      invoice.jobId.toLowerCase().includes(search)
                    );
                  }
                  if (searchField === "invoice") return invoice.id.toLowerCase().includes(search);
                  if (searchField === "customer") return invoice.customer.toLowerCase().includes(search);
                  if (searchField === "jobId") return invoice.jobId.toLowerCase().includes(search);
                  return true;
                })
                .map((invoice) => (
                <TableRow 
                  key={invoice.id} 
                  className="cursor-pointer hover:bg-muted/50"
                  onClick={() => handleEditInvoice(invoice)}
                >
                  <TableCell className="font-mono">{invoice.id}</TableCell>
                  <TableCell className="font-mono text-sm">{invoice.jobId}</TableCell>
                  <TableCell className="font-medium">{invoice.customer}</TableCell>
                  <TableCell className="font-semibold">{invoice.amount}</TableCell>
                  <TableCell>{invoice.date}</TableCell>
                  <TableCell>{invoice.dueDate}</TableCell>
                  <TableCell>
                    <Badge variant={getStatusColor(invoice.status)}>
                      {invoice.status.replace('_', ' ')}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center justify-center">
                      {invoice.autoGenerated ? (
                        <CheckCircle className="w-4 h-4 text-success" />
                      ) : (
                        <span className="text-xs text-muted-foreground">Manual</span>
                      )}
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      <CreateInvoiceModal open={createInvoiceOpen} onOpenChange={setCreateInvoiceOpen} />
      <EditInvoiceModal 
        open={editInvoiceOpen} 
        onOpenChange={setEditInvoiceOpen} 
        invoice={selectedInvoice}
      />
    </div>
  );
}
