import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "pt" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "header.notifications": "Notifications",
    "header.viewAllNotifications": "View all notifications",
    "header.profile": "Profile",
    "header.settings": "Settings",
    "header.logout": "Logout",
    "header.newAppointment": "New appointment",
    "header.paymentReceived": "Payment received",
    "header.jobCompleted": "Job completed",
    "header.minAgo": "min ago",
    "header.hourAgo": "hour ago",
    "header.hoursAgo": "hours ago",
    
    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.view": "View",
    "common.viewDetails": "View Details",
    "common.close": "Close",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.all": "All",
    "common.allRoles": "All Roles",
    "common.allStatus": "All Status",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.status": "Status",
    "common.actions": "Actions",
    "common.name": "Name",
    "common.email": "Email",
    "common.phone": "Phone",
    "common.address": "Address",
    "common.date": "Date",
    "common.time": "Time",
    "common.add": "Add",
    "common.new": "New",
    "common.confirm": "Confirm",
    "common.yes": "Yes",
    "common.no": "No",
    
    // Settings tabs
    "settings.profile": "Profile",
    "settings.company": "Company",
    "settings.notifications": "Notifications",
    "settings.billing": "Billing",
    "settings.team": "Team",
    "settings.security": "Security",
    "settings.integrations": "Integrations",
    
    // Settings - Profile
    "settings.personalInfo": "Personal Information",
    "settings.updateProfileInfo": "Update your profile information",
    "settings.changePhoto": "Change Photo",
    "settings.fullName": "Full Name",
    "settings.enterFullName": "Enter your full name",
    "settings.enterEmail": "Enter your email",
    "settings.saveChanges": "Save Changes",
    
    // Settings - Company
    "settings.companyInfo": "Company Information",
    "settings.businessSettings": "Business and operational settings",
    "settings.companyName": "Company Name",
    "settings.businessAddress": "Business Address",
    "settings.businessEmail": "Business Email",
    "settings.businessPhone": "Business Phone",
    "settings.timezone": "Timezone",
    "settings.currency": "Currency",
    "settings.language": "Language",
    "settings.businessHours": "Business Hours",
    "settings.setOperatingHours": "Set operating hours for each day",
    "settings.to": "to",
    "settings.closed": "Closed",
    
    // Settings - Notifications
    "settings.emailNotifications": "Email Notifications",
    "settings.smsNotifications": "SMS Notifications",
    "settings.pushNotifications": "Push Notifications",
    "settings.jobUpdates": "Job Updates",
    "settings.paymentNotifications": "Payment Notifications",
    "settings.weeklyReports": "Weekly Reports",
    "settings.marketingEmails": "Marketing Emails",
    
    // Settings - Team
    "settings.teamMembers": "Team Members",
    "settings.manageTeam": "Manage your team members and their roles",
    "settings.inviteMember": "Invite Member",
    "settings.pending": "Pending",
    "settings.roles": "Roles",
    "settings.permissions": "Permissions",
    "settings.viewPermissions": "View Permissions",
    "settings.createRole": "Create Role",
    
    // Settings - Security
    "settings.changePassword": "Change Password",
    "settings.currentPassword": "Current Password",
    "settings.newPassword": "New Password",
    "settings.confirmPassword": "Confirm Password",
    "settings.twoFactor": "Two-Factor Authentication",
    "settings.sessionTimeout": "Session Timeout",
    "settings.enterCurrentPassword": "Enter current password",
    "settings.enterNewPassword": "Enter new password",
    "settings.confirmNewPassword": "Confirm new password",
    "settings.enable2FA": "Enable Two-Factor Authentication",
    "settings.accountProtected": "Your account is protected with 2FA",
    "settings.protectWith2FA": "Protect your account with 2FA",
    "settings.authMethod": "Authentication Method",
    "settings.authenticatorApp": "Authenticator App",
    "settings.securityPolicies": "Security Policies",
    "settings.configureSecurityReqs": "Configure security requirements for your organization",
    "settings.sessionTimeoutMinutes": "Session Timeout (minutes)",
    "settings.minPasswordLength": "Minimum Password Length",
    "settings.minutes": "minutes",
    "settings.hour": "hour",
    "settings.hours": "hours",
    "settings.characters": "characters",
    "settings.requireSpecialChars": "Require Special Characters",
    "settings.passwordsMustInclude": "Passwords must include special characters",
    "settings.updateAccountPassword": "Update your account password",
    "settings.addExtraSecurity": "Add an extra layer of security to your account",

    // Settings - Notifications Extended
    "settings.controlEmailNotifications": "Control how and when email notifications are sent",
    "settings.jobUpdatesDesc": "Receive emails about job status changes",
    "settings.paymentNotificationsDesc": "Receive emails about received payments",
    "settings.weeklyReportsDesc": "Receive summary reports weekly",
    "settings.marketingEmailsDesc": "Receive updates about new features and promotions",
    "settings.smsPushNotifications": "SMS & Push Notifications",
    "settings.configureMobileNotifications": "Configure mobile notifications",
    "settings.enableSmsNotifications": "Enable SMS notifications",
    "settings.jobReminders": "Job Reminders",
    "settings.jobRemindersDesc": "Automatic reminders for upcoming jobs",
    "settings.paymentAlerts": "Payment Alerts",
    "settings.paymentAlertsDesc": "Notifications for payments and overdue invoices",
    "settings.feedbackRequests": "Feedback Requests",
    "settings.feedbackRequestsDesc": "Alerts when customers leave reviews",
    "settings.systemAlerts": "System Alerts",
    "settings.systemAlertsDesc": "Important system notifications",

    // Settings - Billing
    "settings.paymentMethods": "Payment Methods",
    "settings.managePaymentMethods": "Manage your payment methods to receive payments",
    "settings.creditDebitCard": "Credit/Debit Card",
    "settings.bankAccount": "Bank Account",
    "settings.ending": "ending",
    "settings.expiresOn": "Expires on",
    "settings.default": "Default",
    "settings.setAsDefault": "Set as Default",
    "settings.addCard": "Add Card",
    "settings.addBankAccount": "Add Bank Account",
    "settings.featureInDevelopment": "Feature in development",

    // Settings - Team
    "settings.manageTeamTitle": "Manage Team",
    "settings.userAccessManagement": "User access management",
    "settings.enterEmailAddress": "Enter email address",
    "settings.admin": "Admin",
    "settings.manager": "Manager",
    "settings.employee": "Employee",
    "settings.invite": "Invite",
    "settings.rolesPermissions": "Roles & Permissions",
    "settings.createEditRoles": "Create and edit roles with specific permissions",
    "settings.fullAccess": "Full access",
    "settings.xPermissions": "permissions",
    "settings.createNewRole": "Create New Role",

    // Settings - Integrations
    "settings.accounting": "Accounting",
    "settings.connectAccountingSoftware": "Connect your accounting software",
    "settings.syncInvoicesPayments": "Sync invoices and payments",
    "settings.connected": "Connected",
    "settings.disconnected": "Disconnected",
    "settings.disconnect": "Disconnect",
    "settings.connect": "Connect",
    "settings.syncInvoices": "Sync Invoices",
    "settings.autoSyncInvoices": "Automatically sync invoices with QuickBooks",
    "settings.syncPayments": "Sync Payments",
    "settings.autoSyncPayments": "Automatically sync payments with QuickBooks",
    "settings.communication": "Communication",
    "settings.smsEmailServices": "SMS and email services",
    "settings.sendSmsNotifications": "Send SMS notifications to customers",
    "settings.sendEmailNotifications": "Send email notifications",
    "settings.automations": "Automations",
    "settings.configureAutoMessages": "Configure automatic messages and reminders",
    "settings.sendAt": "Send at",
    "settings.onlyIfUnpaid": "Only if unpaid",

    // Settings Page Header
    "settings.title": "Settings",
    "settings.description": "Manage system settings and preferences",

    // Schedule
    "schedule.title": "Schedule",
    "schedule.subtitle": "Manage your cleaning schedule",
    "schedule.newJob": "New Job",
    "schedule.scheduleManagement": "Schedule Management",
    
    // Jobs
    "jobs.title": "Recent Jobs",
    "jobs.subtitle": "View history of all cleaning jobs",
    "jobs.totalJobs": "Total Jobs",
    "jobs.completed": "Completed",
    "jobs.inProgress": "In Progress",
    "jobs.scheduled": "Scheduled",
    "jobs.revenue": "Revenue",
    "jobs.cancelled": "Cancelled",
    "jobs.thisMonth": "This month",
    "jobs.completionRate": "completion rate",
    "jobs.activeNow": "Active now",
    "jobs.jobId": "Job ID",
    "jobs.customer": "Customer",
    "jobs.service": "Service",
    "jobs.dateTime": "Date & Time",
    "jobs.staff": "Staff",
    "jobs.duration": "Duration",
    "jobs.amount": "Amount",
    
    // Customers
    "customers.title": "Customers",
    "customers.subtitle": "Manage your customer relationships and profiles",
    "customers.addCustomer": "Add Customer",
    "customers.newCustomers": "New Customers",
    "customers.activeCustomers": "Active Customers",
    "customers.inactiveCustomers": "Inactive Customers",
    "customers.totalCustomers": "Total Customers",
    "customers.recurringCustomers": "Recurring Customers",
    "customers.contactList": "Contact List",
    "customers.lastService": "Last Service",
    "customers.totalJobs": "Total Jobs",
    
    // Dashboard
    "dashboard.welcome": "Welcome back",
    "dashboard.subtitle": "Here's what's happening with your cleaning business today.",
    "dashboard.monthlyRevenue": "Monthly Revenue",
    "dashboard.activeCustomers": "Active Customers",
    "dashboard.jobsThisWeek": "Jobs this Week",
    "dashboard.growthRate": "Growth Rate",
    "dashboard.completedToday": "Completed Today",
    "dashboard.scheduled": "Scheduled",
    "dashboard.activeStaff": "Active Staff",
    "dashboard.upcomingJobs": "Upcoming Jobs",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.todaysAgenda": "Today's Agenda",
    
    // Agenda
    "agenda.job": "Job",
    "agenda.booking": "Booking",
    "agenda.visit": "Visit",
    "agenda.appointment": "Appointment",
    "agenda.scheduled": "Scheduled",
    "agenda.inProgress": "In Progress",
    "agenda.completed": "Completed",
    "agenda.cancelled": "Cancelled",
    
    // Common
    "common.viewAll": "View All",
    "booking.title": "Online Booking",
    "booking.subtitle": "Manage your online bookings",
    "booking.newBooking": "New Booking",
    "booking.recentBookings": "Recent Bookings",
    "booking.onlineBookings": "Online Bookings",
    "booking.conversionRate": "Conversion Rate",
    "booking.averageBooking": "Average Booking",
    "booking.responseTime": "Response Time",
    "booking.confirmed": "Confirmed",
    "booking.pending": "Pending",
    "booking.cancelled": "Cancelled",
    
    // Payroll
    "payroll.title": "Payroll",
    "payroll.employee": "Employee",
    "payroll.allEmployees": "All employees",
    "payroll.searchEmployee": "Search employee...",
    "payroll.noEmployeeFound": "No employee found.",
    "payroll.selectStatus": "Select status",
    "payroll.paid": "Paid",
    "payroll.overdue": "Overdue",
    "payroll.startDate": "Start Date",
    "payroll.endDate": "End Date",
    "payroll.select": "Select",
    "payroll.filterApplied": "Filter applied",
    "payroll.recordsFound": "records found.",
    "payroll.filtersCleared": "Filters cleared",
    "payroll.showingAllRecords": "Showing all records.",
    
    // Users
    "users.title": "Users",
    "users.subtitle": "Manage users and system permissions",
    "users.newUser": "New User",
    "users.managePermissions": "Manage Permissions",
    "users.fullName": "Full Name",
    "users.initialDate": "Initial Date",
    "users.updatedSuccessfully": "updated successfully!",
    "users.removedSuccessfully": "removed successfully!",
    "users.confirmDeletion": "Confirm Deletion",
    "users.deleteConfirmation": "Are you sure you want to delete the user",
    "users.cannotBeUndone": "This action cannot be undone.",
    "users.editUser": "Edit User",
    "users.updateUserInfo": "Update the user information below.",
    "users.selectProfile": "Select profile",
    "users.selectStatus": "Select status",
  },
  pt: {
    // Header
    "header.notifications": "Notificações",
    "header.viewAllNotifications": "Ver todas as notificações",
    "header.profile": "Perfil",
    "header.settings": "Configurações",
    "header.logout": "Sair",
    "header.newAppointment": "Novo agendamento",
    "header.paymentReceived": "Pagamento recebido",
    "header.jobCompleted": "Serviço concluído",
    "header.minAgo": "min atrás",
    "header.hourAgo": "hora atrás",
    "header.hoursAgo": "horas atrás",
    
    // Common
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.delete": "Excluir",
    "common.edit": "Editar",
    "common.view": "Ver",
    "common.viewDetails": "Ver Detalhes",
    "common.close": "Fechar",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.all": "Todos",
    "common.allRoles": "Todas as Funções",
    "common.allStatus": "Todos os Status",
    "common.active": "Ativo",
    "common.inactive": "Inativo",
    "common.status": "Status",
    "common.actions": "Ações",
    "common.name": "Nome",
    "common.email": "E-mail",
    "common.phone": "Telefone",
    "common.address": "Endereço",
    "common.date": "Data",
    "common.time": "Horário",
    "common.add": "Adicionar",
    "common.new": "Novo",
    "common.confirm": "Confirmar",
    "common.yes": "Sim",
    "common.no": "Não",
    
    // Settings tabs
    "settings.profile": "Perfil",
    "settings.company": "Empresa",
    "settings.notifications": "Notificações",
    "settings.billing": "Pagamentos",
    "settings.team": "Equipe",
    "settings.security": "Segurança",
    "settings.integrations": "Integrações",
    
    // Settings - Profile
    "settings.personalInfo": "Informações Pessoais",
    "settings.updateProfileInfo": "Atualize suas informações de perfil",
    "settings.changePhoto": "Alterar Foto",
    "settings.fullName": "Nome Completo",
    "settings.enterFullName": "Digite seu nome completo",
    "settings.enterEmail": "Digite seu e-mail",
    "settings.saveChanges": "Salvar Alterações",
    
    // Settings - Company
    "settings.companyInfo": "Informações da Empresa",
    "settings.businessSettings": "Configurações operacionais e de negócio",
    "settings.companyName": "Nome da Empresa",
    "settings.businessAddress": "Endereço Comercial",
    "settings.businessEmail": "E-mail Comercial",
    "settings.businessPhone": "Telefone Comercial",
    "settings.timezone": "Fuso Horário",
    "settings.currency": "Moeda",
    "settings.language": "Idioma",
    "settings.businessHours": "Horário de Funcionamento",
    "settings.setOperatingHours": "Defina o horário de operação para cada dia",
    "settings.to": "até",
    "settings.closed": "Fechado",
    
    // Settings - Notifications
    "settings.emailNotifications": "Notificações por E-mail",
    "settings.smsNotifications": "Notificações por SMS",
    "settings.pushNotifications": "Notificações Push",
    "settings.jobUpdates": "Atualizações de Serviços",
    "settings.paymentNotifications": "Notificações de Pagamento",
    "settings.weeklyReports": "Relatórios Semanais",
    "settings.marketingEmails": "E-mails de Marketing",
    
    // Settings - Team
    "settings.teamMembers": "Membros da Equipe",
    "settings.manageTeam": "Gerencie os membros da sua equipe e seus papéis",
    "settings.inviteMember": "Convidar Membro",
    "settings.pending": "Pendente",
    "settings.roles": "Funções",
    "settings.permissions": "Permissões",
    "settings.viewPermissions": "Ver Permissões",
    "settings.createRole": "Criar Função",
    
    // Settings - Security
    "settings.changePassword": "Alterar Senha",
    "settings.currentPassword": "Senha Atual",
    "settings.newPassword": "Nova Senha",
    "settings.confirmPassword": "Confirmar Senha",
    "settings.twoFactor": "Autenticação de Dois Fatores",
    "settings.sessionTimeout": "Tempo Limite de Sessão",
    "settings.enterCurrentPassword": "Digite a senha atual",
    "settings.enterNewPassword": "Digite a nova senha",
    "settings.confirmNewPassword": "Confirme a nova senha",
    "settings.enable2FA": "Habilitar Autenticação de Dois Fatores",
    "settings.accountProtected": "Sua conta está protegida com 2FA",
    "settings.protectWith2FA": "Proteja sua conta com 2FA",
    "settings.authMethod": "Método de Autenticação",
    "settings.authenticatorApp": "Aplicativo Autenticador",
    "settings.securityPolicies": "Políticas de Segurança",
    "settings.configureSecurityReqs": "Configure os requisitos de segurança para sua organização",
    "settings.sessionTimeoutMinutes": "Tempo Limite da Sessão (minutos)",
    "settings.minPasswordLength": "Comprimento Mínimo da Senha",
    "settings.minutes": "minutos",
    "settings.hour": "hora",
    "settings.hours": "horas",
    "settings.characters": "caracteres",
    "settings.requireSpecialChars": "Exigir Caracteres Especiais",
    "settings.passwordsMustInclude": "As senhas devem incluir caracteres especiais",
    "settings.updateAccountPassword": "Atualize a senha da sua conta",
    "settings.addExtraSecurity": "Adicione uma camada extra de segurança à sua conta",

    // Settings - Notifications Extended
    "settings.controlEmailNotifications": "Controle como e quando as notificações por e-mail são enviadas",
    "settings.jobUpdatesDesc": "Receba e-mails sobre mudanças de status dos jobs",
    "settings.paymentNotificationsDesc": "Receba e-mails sobre pagamentos recebidos",
    "settings.weeklyReportsDesc": "Receba relatórios resumidos semanalmente",
    "settings.marketingEmailsDesc": "Receba atualizações sobre novos recursos e promoções",
    "settings.smsPushNotifications": "SMS & Notificações Push",
    "settings.configureMobileNotifications": "Configure as notificações móveis",
    "settings.enableSmsNotifications": "Habilitar notificações por SMS",
    "settings.jobReminders": "Lembretes de Jobs",
    "settings.jobRemindersDesc": "Lembretes automáticos para jobs futuros",
    "settings.paymentAlerts": "Alertas de Pagamento",
    "settings.paymentAlertsDesc": "Notificações de pagamentos e faturas vencidas",
    "settings.feedbackRequests": "Solicitações de Feedback",
    "settings.feedbackRequestsDesc": "Alertas quando clientes deixam avaliações",
    "settings.systemAlerts": "Alertas do Sistema",
    "settings.systemAlertsDesc": "Notificações importantes do sistema",

    // Settings - Billing
    "settings.paymentMethods": "Métodos de Pagamento",
    "settings.managePaymentMethods": "Gerencie seus métodos de pagamento para receber pagamentos",
    "settings.creditDebitCard": "Cartão de Crédito/Débito",
    "settings.bankAccount": "Conta Bancária",
    "settings.ending": "final",
    "settings.expiresOn": "Expira em",
    "settings.default": "Padrão",
    "settings.setAsDefault": "Definir como Padrão",
    "settings.addCard": "Adicionar Cartão",
    "settings.addBankAccount": "Adicionar Conta Bancária",
    "settings.featureInDevelopment": "Recurso em desenvolvimento",

    // Settings - Team
    "settings.manageTeamTitle": "Gerenciar Equipe",
    "settings.userAccessManagement": "Gerenciamento de acesso de usuários",
    "settings.enterEmailAddress": "Digite o endereço de e-mail",
    "settings.admin": "Admin",
    "settings.manager": "Gerente",
    "settings.employee": "Funcionário",
    "settings.invite": "Convidar",
    "settings.rolesPermissions": "Funções & Permissões",
    "settings.createEditRoles": "Crie e edite funções com permissões específicas",
    "settings.fullAccess": "Acesso total",
    "settings.xPermissions": "permissões",
    "settings.createNewRole": "Criar Nova Função",

    // Settings - Integrations
    "settings.accounting": "Contabilidade",
    "settings.connectAccountingSoftware": "Conecte seu software de contabilidade",
    "settings.syncInvoicesPayments": "Sincronize faturas e pagamentos",
    "settings.connected": "Conectado",
    "settings.disconnected": "Desconectado",
    "settings.disconnect": "Desconectar",
    "settings.connect": "Conectar",
    "settings.syncInvoices": "Sincronizar Faturas",
    "settings.autoSyncInvoices": "Sincronizar faturas automaticamente com QuickBooks",
    "settings.syncPayments": "Sincronizar Pagamentos",
    "settings.autoSyncPayments": "Sincronizar pagamentos automaticamente com QuickBooks",
    "settings.communication": "Comunicação",
    "settings.smsEmailServices": "Serviços de SMS e e-mail",
    "settings.sendSmsNotifications": "Envie notificações SMS para clientes",
    "settings.sendEmailNotifications": "Envie notificações por e-mail",
    "settings.automations": "Automações",
    "settings.configureAutoMessages": "Configure mensagens e lembretes automáticos",
    "settings.sendAt": "Enviar às",
    "settings.onlyIfUnpaid": "Somente se não pago",

    // Settings Page Header
    "settings.title": "Configurações",
    "settings.description": "Gerencie as configurações do sistema e preferências",

    // Schedule
    "schedule.title": "Agenda",
    "schedule.subtitle": "Gerencie sua agenda de limpeza",
    "schedule.newJob": "Novo Serviço",
    "schedule.scheduleManagement": "Gerenciamento de Agenda",
    
    // Jobs
    "jobs.title": "Serviços Recentes",
    "jobs.subtitle": "Visualize o histórico de todos os serviços de limpeza",
    "jobs.totalJobs": "Total de Serviços",
    "jobs.completed": "Concluídos",
    "jobs.inProgress": "Em Andamento",
    "jobs.scheduled": "Agendados",
    "jobs.revenue": "Receita",
    "jobs.cancelled": "Cancelados",
    "jobs.thisMonth": "Este mês",
    "jobs.completionRate": "taxa de conclusão",
    "jobs.activeNow": "Ativos agora",
    "jobs.jobId": "ID do Serviço",
    "jobs.customer": "Cliente",
    "jobs.service": "Serviço",
    "jobs.dateTime": "Data e Hora",
    "jobs.staff": "Equipe",
    "jobs.duration": "Duração",
    "jobs.amount": "Valor",
    
    // Customers
    "customers.title": "Clientes",
    "customers.subtitle": "Gerencie seus relacionamentos e perfis de clientes",
    "customers.addCustomer": "Adicionar Cliente",
    "customers.newCustomers": "Novos Clientes",
    "customers.activeCustomers": "Clientes Ativos",
    "customers.inactiveCustomers": "Clientes Inativos",
    "customers.totalCustomers": "Total de Clientes",
    "customers.recurringCustomers": "Clientes Recorrentes",
    "customers.contactList": "Lista de Contatos",
    "customers.lastService": "Último Serviço",
    "customers.totalJobs": "Total de Serviços",
    
    // Dashboard
    "dashboard.welcome": "Bem-vindo de volta",
    "dashboard.subtitle": "Veja o que está acontecendo com seu negócio de limpeza hoje.",
    "dashboard.monthlyRevenue": "Receita Mensal",
    "dashboard.activeCustomers": "Clientes Ativos",
    "dashboard.jobsThisWeek": "Serviços da Semana",
    "dashboard.growthRate": "Taxa de Crescimento",
    "dashboard.completedToday": "Concluídos Hoje",
    "dashboard.scheduled": "Agendados",
    "dashboard.activeStaff": "Equipe Ativa",
    "dashboard.upcomingJobs": "Próximos Serviços",
    "dashboard.recentActivity": "Atividade Recente",
    "dashboard.todaysAgenda": "Agenda de Hoje",
    
    // Agenda
    "agenda.job": "Serviço",
    "agenda.booking": "Reserva",
    "agenda.visit": "Visita",
    "agenda.appointment": "Compromisso",
    "agenda.scheduled": "Agendado",
    "agenda.inProgress": "Em Andamento",
    "agenda.completed": "Concluído",
    "agenda.cancelled": "Cancelado",
    
    // Common
    "common.viewAll": "Ver Tudo",
    // Booking
    "booking.title": "Agendamento Online",
    "booking.subtitle": "Gerencie seus agendamentos online",
    "booking.newBooking": "Novo Agendamento",
    "booking.recentBookings": "Agendamentos Recentes",
    "booking.onlineBookings": "Agendamentos Online",
    "booking.conversionRate": "Taxa de Conversão",
    "booking.averageBooking": "Ticket Médio",
    "booking.responseTime": "Tempo de Resposta",
    "booking.confirmed": "Confirmado",
    "booking.pending": "Pendente",
    "booking.cancelled": "Cancelado",
    
    // Payroll
    "payroll.title": "Folha de Pagamento",
    "payroll.employee": "Funcionário",
    "payroll.allEmployees": "Todos os funcionários",
    "payroll.searchEmployee": "Buscar funcionário...",
    "payroll.noEmployeeFound": "Nenhum funcionário encontrado.",
    "payroll.selectStatus": "Selecionar status",
    "payroll.paid": "Pago",
    "payroll.overdue": "Atrasado",
    "payroll.startDate": "Data Início",
    "payroll.endDate": "Data Fim",
    "payroll.select": "Selecionar",
    "payroll.filterApplied": "Filtro aplicado",
    "payroll.recordsFound": "registros encontrados.",
    "payroll.filtersCleared": "Filtros limpos",
    "payroll.showingAllRecords": "Mostrando todos os registros.",
    
    // Users
    "users.title": "Usuários",
    "users.subtitle": "Gerencie usuários e permissões do sistema",
    "users.newUser": "Novo Usuário",
    "users.managePermissions": "Gerenciar Permissões",
    "users.fullName": "Nome Completo",
    "users.initialDate": "Data de Início",
    "users.updatedSuccessfully": "atualizado com sucesso!",
    "users.removedSuccessfully": "removido com sucesso!",
    "users.confirmDeletion": "Confirmar Exclusão",
    "users.deleteConfirmation": "Tem certeza que deseja excluir o usuário",
    "users.cannotBeUndone": "Esta ação não pode ser desfeita.",
    "users.editUser": "Editar Usuário",
    "users.updateUserInfo": "Atualize as informações do usuário abaixo.",
    "users.selectProfile": "Selecione o perfil",
    "users.selectStatus": "Selecione o status",
  },
  es: {
    // Header
    "header.notifications": "Notificaciones",
    "header.viewAllNotifications": "Ver todas las notificaciones",
    "header.profile": "Perfil",
    "header.settings": "Configuración",
    "header.logout": "Cerrar sesión",
    "header.newAppointment": "Nueva cita",
    "header.paymentReceived": "Pago recibido",
    "header.jobCompleted": "Trabajo completado",
    "header.minAgo": "min atrás",
    "header.hourAgo": "hora atrás",
    "header.hoursAgo": "horas atrás",
    
    // Common
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.view": "Ver",
    "common.viewDetails": "Ver Detalles",
    "common.close": "Cerrar",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.all": "Todos",
    "common.allRoles": "Todos los Roles",
    "common.allStatus": "Todos los Estados",
    "common.active": "Activo",
    "common.inactive": "Inactivo",
    "common.status": "Estado",
    "common.actions": "Acciones",
    "common.name": "Nombre",
    "common.email": "Correo",
    "common.phone": "Teléfono",
    "common.address": "Dirección",
    "common.date": "Fecha",
    "common.time": "Hora",
    "common.add": "Agregar",
    "common.new": "Nuevo",
    "common.confirm": "Confirmar",
    "common.yes": "Sí",
    "common.no": "No",
    
    // Settings tabs
    "settings.profile": "Perfil",
    "settings.company": "Empresa",
    "settings.notifications": "Notificaciones",
    "settings.billing": "Facturación",
    "settings.team": "Equipo",
    "settings.security": "Seguridad",
    "settings.integrations": "Integraciones",
    
    // Settings - Profile
    "settings.personalInfo": "Información Personal",
    "settings.updateProfileInfo": "Actualiza tu información de perfil",
    "settings.changePhoto": "Cambiar Foto",
    "settings.fullName": "Nombre Completo",
    "settings.enterFullName": "Ingresa tu nombre completo",
    "settings.enterEmail": "Ingresa tu correo",
    "settings.saveChanges": "Guardar Cambios",
    
    // Settings - Company
    "settings.companyInfo": "Información de la Empresa",
    "settings.businessSettings": "Configuración operacional y de negocio",
    "settings.companyName": "Nombre de la Empresa",
    "settings.businessAddress": "Dirección Comercial",
    "settings.businessEmail": "Correo Comercial",
    "settings.businessPhone": "Teléfono Comercial",
    "settings.timezone": "Zona Horaria",
    "settings.currency": "Moneda",
    "settings.language": "Idioma",
    "settings.businessHours": "Horario de Atención",
    "settings.setOperatingHours": "Define el horario de operación para cada día",
    "settings.to": "a",
    "settings.closed": "Cerrado",
    
    // Settings - Notifications
    "settings.emailNotifications": "Notificaciones por Correo",
    "settings.smsNotifications": "Notificaciones por SMS",
    "settings.pushNotifications": "Notificaciones Push",
    "settings.jobUpdates": "Actualizaciones de Trabajos",
    "settings.paymentNotifications": "Notificaciones de Pago",
    "settings.weeklyReports": "Reportes Semanales",
    "settings.marketingEmails": "Correos de Marketing",
    
    // Settings - Team
    "settings.teamMembers": "Miembros del Equipo",
    "settings.manageTeam": "Administra los miembros de tu equipo y sus roles",
    "settings.inviteMember": "Invitar Miembro",
    "settings.pending": "Pendiente",
    "settings.roles": "Roles",
    "settings.permissions": "Permisos",
    "settings.viewPermissions": "Ver Permisos",
    "settings.createRole": "Crear Rol",
    
    // Settings - Security
    "settings.changePassword": "Cambiar Contraseña",
    "settings.currentPassword": "Contraseña Actual",
    "settings.newPassword": "Nueva Contraseña",
    "settings.confirmPassword": "Confirmar Contraseña",
    "settings.twoFactor": "Autenticación de Dos Factores",
    "settings.sessionTimeout": "Tiempo de Sesión",
    "settings.enterCurrentPassword": "Ingresa la contraseña actual",
    "settings.enterNewPassword": "Ingresa la nueva contraseña",
    "settings.confirmNewPassword": "Confirma la nueva contraseña",
    "settings.enable2FA": "Habilitar Autenticación de Dos Factores",
    "settings.accountProtected": "Tu cuenta está protegida con 2FA",
    "settings.protectWith2FA": "Protege tu cuenta con 2FA",
    "settings.authMethod": "Método de Autenticación",
    "settings.authenticatorApp": "Aplicación Autenticadora",
    "settings.securityPolicies": "Políticas de Seguridad",
    "settings.configureSecurityReqs": "Configura los requisitos de seguridad para tu organización",
    "settings.sessionTimeoutMinutes": "Tiempo de Sesión (minutos)",
    "settings.minPasswordLength": "Longitud Mínima de Contraseña",
    "settings.minutes": "minutos",
    "settings.hour": "hora",
    "settings.hours": "horas",
    "settings.characters": "caracteres",
    "settings.requireSpecialChars": "Requerir Caracteres Especiales",
    "settings.passwordsMustInclude": "Las contraseñas deben incluir caracteres especiales",
    "settings.updateAccountPassword": "Actualiza la contraseña de tu cuenta",
    "settings.addExtraSecurity": "Agrega una capa extra de seguridad a tu cuenta",

    // Settings - Notifications Extended
    "settings.controlEmailNotifications": "Controla cómo y cuándo se envían las notificaciones por correo",
    "settings.jobUpdatesDesc": "Recibe correos sobre cambios de estado de trabajos",
    "settings.paymentNotificationsDesc": "Recibe correos sobre pagos recibidos",
    "settings.weeklyReportsDesc": "Recibe reportes resumidos semanalmente",
    "settings.marketingEmailsDesc": "Recibe actualizaciones sobre nuevas funciones y promociones",
    "settings.smsPushNotifications": "SMS & Notificaciones Push",
    "settings.configureMobileNotifications": "Configura las notificaciones móviles",
    "settings.enableSmsNotifications": "Habilitar notificaciones por SMS",
    "settings.jobReminders": "Recordatorios de Trabajos",
    "settings.jobRemindersDesc": "Recordatorios automáticos para trabajos futuros",
    "settings.paymentAlerts": "Alertas de Pago",
    "settings.paymentAlertsDesc": "Notificaciones de pagos y facturas vencidas",
    "settings.feedbackRequests": "Solicitudes de Comentarios",
    "settings.feedbackRequestsDesc": "Alertas cuando los clientes dejan reseñas",
    "settings.systemAlerts": "Alertas del Sistema",
    "settings.systemAlertsDesc": "Notificaciones importantes del sistema",

    // Settings - Billing
    "settings.paymentMethods": "Métodos de Pago",
    "settings.managePaymentMethods": "Administra tus métodos de pago para recibir pagos",
    "settings.creditDebitCard": "Tarjeta de Crédito/Débito",
    "settings.bankAccount": "Cuenta Bancaria",
    "settings.ending": "terminada en",
    "settings.expiresOn": "Expira en",
    "settings.default": "Predeterminado",
    "settings.setAsDefault": "Establecer como Predeterminado",
    "settings.addCard": "Agregar Tarjeta",
    "settings.addBankAccount": "Agregar Cuenta Bancaria",
    "settings.featureInDevelopment": "Función en desarrollo",

    // Settings - Team
    "settings.manageTeamTitle": "Gestionar Equipo",
    "settings.userAccessManagement": "Gestión de acceso de usuarios",
    "settings.enterEmailAddress": "Ingresa la dirección de correo",
    "settings.admin": "Admin",
    "settings.manager": "Gerente",
    "settings.employee": "Empleado",
    "settings.invite": "Invitar",
    "settings.rolesPermissions": "Roles y Permisos",
    "settings.createEditRoles": "Crea y edita roles con permisos específicos",
    "settings.fullAccess": "Acceso total",
    "settings.xPermissions": "permisos",
    "settings.createNewRole": "Crear Nuevo Rol",

    // Settings - Integrations
    "settings.accounting": "Contabilidad",
    "settings.connectAccountingSoftware": "Conecta tu software de contabilidad",
    "settings.syncInvoicesPayments": "Sincroniza facturas y pagos",
    "settings.connected": "Conectado",
    "settings.disconnected": "Desconectado",
    "settings.disconnect": "Desconectar",
    "settings.connect": "Conectar",
    "settings.syncInvoices": "Sincronizar Facturas",
    "settings.autoSyncInvoices": "Sincronizar facturas automáticamente con QuickBooks",
    "settings.syncPayments": "Sincronizar Pagos",
    "settings.autoSyncPayments": "Sincronizar pagos automáticamente con QuickBooks",
    "settings.communication": "Comunicación",
    "settings.smsEmailServices": "Servicios de SMS y correo",
    "settings.sendSmsNotifications": "Envía notificaciones SMS a clientes",
    "settings.sendEmailNotifications": "Envía notificaciones por correo",
    "settings.automations": "Automatizaciones",
    "settings.configureAutoMessages": "Configura mensajes y recordatorios automáticos",
    "settings.sendAt": "Enviar a las",
    "settings.onlyIfUnpaid": "Solo si no está pagado",

    // Settings Page Header
    "settings.title": "Configuración",
    "settings.description": "Administra la configuración del sistema y preferencias",

    // Schedule
    "schedule.title": "Agenda",
    "schedule.subtitle": "Administra tu agenda de limpieza",
    "schedule.newJob": "Nuevo Trabajo",
    "schedule.scheduleManagement": "Gestión de Agenda",
    
    // Jobs
    "jobs.title": "Trabajos Recientes",
    "jobs.subtitle": "Ver historial de todos los trabajos de limpieza",
    "jobs.totalJobs": "Total de Trabajos",
    "jobs.completed": "Completados",
    "jobs.inProgress": "En Progreso",
    "jobs.scheduled": "Programados",
    "jobs.revenue": "Ingresos",
    "jobs.cancelled": "Cancelados",
    "jobs.thisMonth": "Este mes",
    "jobs.completionRate": "tasa de finalización",
    "jobs.activeNow": "Activos ahora",
    "jobs.jobId": "ID del Trabajo",
    "jobs.customer": "Cliente",
    "jobs.service": "Servicio",
    "jobs.dateTime": "Fecha y Hora",
    "jobs.staff": "Personal",
    "jobs.duration": "Duración",
    "jobs.amount": "Monto",
    
    // Customers
    "customers.title": "Clientes",
    "customers.subtitle": "Administra tus relaciones y perfiles de clientes",
    "customers.addCustomer": "Agregar Cliente",
    "customers.newCustomers": "Clientes Nuevos",
    "customers.activeCustomers": "Clientes Activos",
    "customers.inactiveCustomers": "Clientes Inactivos",
    "customers.totalCustomers": "Total de Clientes",
    "customers.recurringCustomers": "Clientes Recurrentes",
    "customers.contactList": "Lista de Contactos",
    "customers.lastService": "Último Servicio",
    "customers.totalJobs": "Total de Trabajos",
    
    // Dashboard
    "dashboard.welcome": "Bienvenido de nuevo",
    "dashboard.subtitle": "Esto es lo que está pasando con tu negocio de limpieza hoy.",
    "dashboard.monthlyRevenue": "Ingresos Mensuales",
    "dashboard.activeCustomers": "Clientes Activos",
    "dashboard.jobsThisWeek": "Trabajos de la Semana",
    "dashboard.growthRate": "Tasa de Crecimiento",
    "dashboard.completedToday": "Completados Hoy",
    "dashboard.scheduled": "Programados",
    "dashboard.activeStaff": "Personal Activo",
    "dashboard.upcomingJobs": "Próximos Trabajos",
    "dashboard.recentActivity": "Actividad Reciente",
    "dashboard.todaysAgenda": "Agenda de Hoy",
    
    // Agenda
    "agenda.job": "Trabajo",
    "agenda.booking": "Reserva",
    "agenda.visit": "Visita",
    "agenda.appointment": "Cita",
    "agenda.scheduled": "Programado",
    "agenda.inProgress": "En Progreso",
    "agenda.completed": "Completado",
    "agenda.cancelled": "Cancelado",
    
    // Common
    "common.viewAll": "Ver Todo",
    // Booking
    "booking.title": "Reservas Online",
    "booking.subtitle": "Administra tus reservas en línea",
    "booking.newBooking": "Nueva Reserva",
    "booking.recentBookings": "Reservas Recientes",
    "booking.onlineBookings": "Reservas Online",
    "booking.conversionRate": "Tasa de Conversión",
    "booking.averageBooking": "Reserva Promedio",
    "booking.responseTime": "Tiempo de Respuesta",
    "booking.confirmed": "Confirmado",
    "booking.pending": "Pendiente",
    "booking.cancelled": "Cancelado",
    
    // Payroll
    "payroll.title": "Nómina",
    "payroll.employee": "Empleado",
    "payroll.allEmployees": "Todos los empleados",
    "payroll.searchEmployee": "Buscar empleado...",
    "payroll.noEmployeeFound": "Ningún empleado encontrado.",
    "payroll.selectStatus": "Seleccionar estado",
    "payroll.paid": "Pagado",
    "payroll.overdue": "Vencido",
    "payroll.startDate": "Fecha Inicio",
    "payroll.endDate": "Fecha Fin",
    "payroll.select": "Seleccionar",
    "payroll.filterApplied": "Filtro aplicado",
    "payroll.recordsFound": "registros encontrados.",
    "payroll.filtersCleared": "Filtros limpiados",
    "payroll.showingAllRecords": "Mostrando todos los registros.",
    
    // Users
    "users.title": "Usuarios",
    "users.subtitle": "Administra usuarios y permisos del sistema",
    "users.newUser": "Nuevo Usuario",
    "users.managePermissions": "Gestionar Permisos",
    "users.fullName": "Nombre Completo",
    "users.initialDate": "Fecha de Inicio",
    "users.updatedSuccessfully": "¡actualizado con éxito!",
    "users.removedSuccessfully": "¡eliminado con éxito!",
    "users.confirmDeletion": "Confirmar Eliminación",
    "users.deleteConfirmation": "¿Estás seguro de que deseas eliminar al usuario",
    "users.cannotBeUndone": "Esta acción no se puede deshacer.",
    "users.editUser": "Editar Usuario",
    "users.updateUserInfo": "Actualiza la información del usuario a continuación.",
    "users.selectProfile": "Seleccionar perfil",
    "users.selectStatus": "Seleccionar estado",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("app-language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
